'use client'

import React, { useState, useEffect } from 'react'
import {
  Star,
  CheckCircle,
  Clock,
  Shield,
  Zap,
  Users,
  Award,
  Target,
  TrendingUp,
  Gift,
  ArrowRight,
  Sparkles,
  Crown,
  Heart,
  Rocket,
} from 'lucide-react'

// Demo data for the Grand Slam Offer
const offerData = {
  title: 'Ultimate Business Transformation Accelerator',
  subtitle: 'The Complete System to Build a 7-Figure Business in 12 Months',
  hero: {
    tagline: 'From Struggling Entrepreneur to Industry Leader',
    description:
      "Join 2,847+ entrepreneurs who've transformed their businesses using our proven system",
    image: '/api/placeholder/600/400',
  },
  components: [
    {
      id: 1,
      title: 'Dream Outcomes',
      icon: Target,
      color: 'from-purple-500 to-pink-500',
      description: "The life-changing results you'll achieve",
      items: [
        'Build a 7-figure business within 12 months',
        'Create multiple passive income streams',
        'Achieve complete financial freedom',
        'Work only 20 hours per week',
        'Travel the world while your business runs itself',
      ],
    },
    {
      id: 2,
      title: 'Proven Solutions',
      icon: CheckCircle,
      color: 'from-blue-500 to-cyan-500',
      description: 'Battle-tested strategies that guarantee success',
      items: [
        'The 90-Day Business Launch Blueprint',
        'Automated Sales Funnel System',
        'High-Converting Marketing Templates',
        'Customer Acquisition Playbook',
        'Scaling & Optimization Framework',
      ],
    },
    {
      id: 3,
      title: 'Value Stack',
      icon: Gift,
      color: 'from-green-500 to-emerald-500',
      description: 'Everything you get in this incredible package',
      items: [
        'Complete Business Blueprint ($2,997 value)',
        'Marketing Automation Suite ($1,497 value)',
        '1-on-1 Strategy Sessions ($997 value)',
        'Private Mastermind Access ($497/month value)',
        'Done-for-You Templates ($797 value)',
      ],
    },
    {
      id: 4,
      title: 'Risk Reversal',
      icon: Shield,
      color: 'from-orange-500 to-red-500',
      description: 'Your success is 100% guaranteed',
      items: [
        '365-Day Money-Back Guarantee',
        'Double Your Money Back if not satisfied',
        'Free coaching until you succeed',
        'Lifetime access to all updates',
        'Success guarantee or full refund',
      ],
    },
    {
      id: 5,
      title: 'Scarcity & Urgency',
      icon: Clock,
      color: 'from-red-500 to-pink-500',
      description: 'Limited time and availability',
      items: [
        'Only 100 spots available this month',
        'Price increases by $500 next week',
        'Bonus package expires in 48 hours',
        'Next cohort starts in 7 days',
        'Early bird pricing ends tonight',
      ],
    },
    {
      id: 6,
      title: 'Social Proof',
      icon: Users,
      color: 'from-indigo-500 to-purple-500',
      description: 'Real results from real people',
      items: [
        '2,847+ successful entrepreneurs',
        'Average ROI of 847% in first year',
        'Featured in Forbes, Entrepreneur, Inc.',
        '98% student satisfaction rate',
        '$47M+ generated by our students',
      ],
    },
    {
      id: 7,
      title: 'Pricing Strategy',
      icon: TrendingUp,
      color: 'from-yellow-500 to-orange-500',
      description: 'Incredible value at an unbeatable price',
      items: [
        'Regular price: $6,785',
        "Today's price: $1,997 (Save $4,788)",
        'Payment plan: 3x $697',
        'ROI guarantee: 10x your investment',
        "Priceless: The freedom you'll gain",
      ],
    },
    {
      id: 8,
      title: 'Objection Handling',
      icon: Award,
      color: 'from-teal-500 to-blue-500',
      description: 'Every concern addressed',
      items: [
        '"I don\'t have time" - System works in 2 hours/day',
        '"I\'m not tech-savvy" - Everything is done-for-you',
        '"I\'ve tried before" - This is different, proven system',
        '"I can\'t afford it" - Payment plans available',
        '"Will it work for me?" - Works in any industry',
      ],
    },
    {
      id: 9,
      title: 'Urgency Amplifiers',
      icon: Zap,
      color: 'from-pink-500 to-rose-500',
      description: 'Why you must act now',
      items: [
        'Limited enrollment closes in 24 hours',
        'Bonus worth $2,000 expires tonight',
        'Price doubles after this promotion',
        'Next available spot is in 6 months',
        'Your competitors are already inside',
      ],
    },
    {
      id: 10,
      title: 'Irresistible Bonuses',
      icon: Crown,
      color: 'from-violet-500 to-purple-500',
      description: 'Exclusive bonuses worth $5,000+',
      items: [
        'Private 1-on-1 Strategy Session ($997 value)',
        'Done-for-You Marketing Campaign ($1,497 value)',
        'Exclusive Mastermind Access ($497/month value)',
        'Personal Brand Blueprint ($797 value)',
        'Lifetime Updates & Support ($1,997 value)',
      ],
    },
    {
      id: 11,
      title: 'Call to Action',
      icon: Rocket,
      color: 'from-emerald-500 to-teal-500',
      description: 'Your transformation starts now',
      items: [
        "Click 'Transform My Business' below",
        'Secure your spot in 30 seconds',
        'Start your journey today',
        'Join the success stories',
        'Your future self will thank you',
      ],
    },
  ],
}

export default function OfferShowcase() {
  const [activeComponent, setActiveComponent] = useState(0)
  const [isVisible, setIsVisible] = useState(false)

  useEffect(() => {
    setIsVisible(true)
  }, [])

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 overflow-hidden">
      {/* Animated Background Elements */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-purple-500/20 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-blue-500/20 rounded-full blur-3xl animate-pulse animate-delay-1000"></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-96 h-96 bg-pink-500/10 rounded-full blur-3xl animate-pulse animate-delay-2000"></div>
      </div>

      {/* Hero Section */}
      <section
        className={`relative z-10 pt-20 pb-16 px-4 transition-all duration-1000 ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-12'}`}
      >
        <div className="max-w-6xl mx-auto text-center">
          <div className="inline-flex items-center space-x-2 bg-gradient-to-r from-purple-500/20 to-pink-500/20 backdrop-blur-sm rounded-full px-6 py-3 border border-purple-500/30 mb-8 animate-fade-in-up">
            <Sparkles className="w-5 h-5 text-yellow-400" />
            <span className="text-white font-medium">Grand Slam Offer</span>
            <Sparkles className="w-5 h-5 text-yellow-400" />
          </div>

          <h1 className="text-5xl md:text-7xl font-bold bg-gradient-to-r from-white via-purple-200 to-pink-200 bg-clip-text text-transparent mb-6 leading-tight animate-fade-in-up animation-delay-200 animate-gradient">
            {offerData.title}
          </h1>

          <p className="text-xl md:text-2xl text-gray-300 mb-8 max-w-4xl mx-auto animate-fade-in-up animation-delay-400">
            {offerData.subtitle}
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center space-y-4 sm:space-y-0 sm:space-x-6 mb-12 animate-fade-in-up animation-delay-600">
            <div className="flex items-center space-x-2 text-yellow-400">
              <Star className="w-5 h-5 fill-current" />
              <Star className="w-5 h-5 fill-current" />
              <Star className="w-5 h-5 fill-current" />
              <Star className="w-5 h-5 fill-current" />
              <Star className="w-5 h-5 fill-current" />
              <span className="text-white ml-2">4.9/5 from 2,847+ entrepreneurs</span>
            </div>
          </div>

          <div className="relative inline-block animate-fade-in-up animation-delay-800">
            <button className="group relative px-8 py-4 bg-gradient-to-r from-purple-600 to-pink-600 text-white font-bold text-lg rounded-full hover:from-purple-700 hover:to-pink-700 transition-all duration-300 transform hover:scale-105 shadow-2xl pulse-glow animate-float">
              <span className="relative z-10 flex items-center space-x-2">
                <span>Start Your Transformation</span>
                <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
              </span>
              <div className="absolute inset-0 bg-gradient-to-r from-purple-600 to-pink-600 rounded-full blur opacity-70 group-hover:opacity-100 transition-opacity"></div>
              <div className="absolute inset-0 shimmer rounded-full"></div>
            </button>
          </div>
        </div>
      </section>

      {/* Components Showcase */}
      <section className="relative z-10 py-16 px-4">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16 animate-fade-in-up">
            <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
              The 11 Components of Success
            </h2>
            <p className="text-xl text-gray-300 max-w-3xl mx-auto">
              Each component is carefully crafted to maximize value and eliminate objections
            </p>
          </div>

          {/* Component Grid */}
          <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-8">
            {offerData.components.map((component, index) => {
              const Icon = component.icon
              return (
                <div
                  key={component.id}
                  className="group relative transform transition-all duration-300 hover:scale-105 hover:-translate-y-2 animate-fade-in-up"
                  style={{ animationDelay: `${index * 100}ms` }}
                >
                  <div className="relative bg-white/5 backdrop-blur-sm rounded-2xl p-8 border border-white/10 hover:border-white/20 transition-all duration-300 h-full">
                    {/* Background Gradient */}
                    <div
                      className={`absolute inset-0 bg-gradient-to-br ${component.color} opacity-5 rounded-2xl`}
                    ></div>

                    {/* Content */}
                    <div className="relative z-10">
                      {/* Header */}
                      <div className="flex items-center space-x-4 mb-6">
                        <div
                          className={`p-3 rounded-xl bg-gradient-to-br ${component.color} shadow-lg`}
                        >
                          <Icon className="w-6 h-6 text-white" />
                        </div>
                        <div>
                          <div className="text-sm text-gray-400 font-medium">
                            Component {component.id}
                          </div>
                          <h3 className="text-xl font-bold text-white">{component.title}</h3>
                        </div>
                      </div>

                      {/* Description */}
                      <p className="text-gray-300 mb-6 leading-relaxed">{component.description}</p>

                      {/* Items */}
                      <div className="space-y-3">
                        {component.items.map((item, itemIndex) => (
                          <div
                            key={itemIndex}
                            className="flex items-start space-x-3 animate-fade-in-left"
                            style={{ animationDelay: `${itemIndex * 100}ms` }}
                          >
                            <CheckCircle className="w-5 h-5 text-green-400 mt-0.5 flex-shrink-0" />
                            <span className="text-gray-200 text-sm leading-relaxed">{item}</span>
                          </div>
                        ))}
                      </div>

                      {/* Hover Effect */}
                      <div className="absolute inset-0 bg-gradient-to-br from-white/5 to-transparent rounded-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      </section>

      {/* Value Proposition */}
      <section className="relative z-10 py-20 px-4">
        <div className="max-w-4xl mx-auto text-center">
          <div className="bg-gradient-to-r from-purple-500/10 to-pink-500/10 backdrop-blur-sm rounded-3xl p-12 border border-purple-500/20 animate-fade-in-up">
            <div className="inline-flex items-center space-x-2 bg-gradient-to-r from-yellow-500/20 to-orange-500/20 rounded-full px-6 py-3 border border-yellow-500/30 mb-8">
              <Crown className="w-5 h-5 text-yellow-400" />
              <span className="text-white font-medium">The Value Equation</span>
              <Crown className="w-5 h-5 text-yellow-400" />
            </div>

            <h3 className="text-3xl md:text-4xl font-bold text-white mb-6">
              Total Value:{' '}
              <span className="text-transparent bg-gradient-to-r from-green-400 to-emerald-400 bg-clip-text">
                $15,785
              </span>
            </h3>

            <div className="text-6xl md:text-7xl font-bold text-white mb-6">
              Your Investment:{' '}
              <span className="text-transparent bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text">
                $1,997
              </span>
            </div>

            <p className="text-xl text-gray-300 mb-8">
              That's a <span className="text-green-400 font-bold">792% value</span> - but the real
              value is the freedom and success you'll achieve
            </p>

            <button className="group relative px-12 py-6 bg-gradient-to-r from-green-600 to-emerald-600 text-white font-bold text-xl rounded-full hover:from-green-700 hover:to-emerald-700 transition-all duration-300 transform hover:scale-105 shadow-2xl animate-glow">
              <span className="relative z-10 flex items-center space-x-3">
                <Heart className="w-6 h-6" />
                <span>Claim Your Transformation</span>
                <Rocket className="w-6 h-6 group-hover:translate-x-1 transition-transform" />
              </span>
              <div className="absolute inset-0 bg-gradient-to-r from-green-600 to-emerald-600 rounded-full blur opacity-70 group-hover:opacity-100 transition-opacity"></div>
              <div className="absolute inset-0 shimmer rounded-full"></div>
            </button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="relative z-10 py-12 px-4 border-t border-white/10">
        <div className="max-w-4xl mx-auto text-center">
          <p className="text-gray-400 mb-4">
            Join thousands of entrepreneurs who've transformed their lives
          </p>
          <div className="flex items-center justify-center space-x-8 text-sm text-gray-500">
            <span>© 2024 Business Transformation</span>
            <span>•</span>
            <span>Privacy Policy</span>
            <span>•</span>
            <span>Terms of Service</span>
          </div>
        </div>
      </footer>

      {/* Custom CSS Animations */}
      <style jsx>{`
        @keyframes fade-in-up {
          from {
            opacity: 0;
            transform: translateY(30px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        @keyframes fade-in-left {
          from {
            opacity: 0;
            transform: translateX(-20px);
          }
          to {
            opacity: 1;
            transform: translateX(0);
          }
        }

        @keyframes glow {
          0%,
          100% {
            box-shadow: 0 0 20px rgba(168, 85, 247, 0.4);
          }
          50% {
            box-shadow: 0 0 40px rgba(168, 85, 247, 0.8);
          }
        }

        @keyframes float {
          0%,
          100% {
            transform: translateY(0px);
          }
          50% {
            transform: translateY(-10px);
          }
        }

        .animate-fade-in-up {
          animation: fade-in-up 0.8s ease-out forwards;
        }

        .animate-fade-in-left {
          animation: fade-in-left 0.5s ease-out forwards;
        }

        .animation-delay-200 {
          animation-delay: 200ms;
        }

        .animation-delay-400 {
          animation-delay: 400ms;
        }

        .animation-delay-600 {
          animation-delay: 600ms;
        }

        .animation-delay-800 {
          animation-delay: 800ms;
        }

        .animate-delay-1000 {
          animation-delay: 1000ms;
        }

        .animate-delay-2000 {
          animation-delay: 2000ms;
        }

        .animate-glow {
          animation: glow 2s ease-in-out infinite;
        }

        .animate-float {
          animation: float 3s ease-in-out infinite;
        }

        /* Gradient text animation */
        @keyframes gradient-shift {
          0% {
            background-position: 0% 50%;
          }
          50% {
            background-position: 100% 50%;
          }
          100% {
            background-position: 0% 50%;
          }
        }

        .animate-gradient {
          background-size: 200% 200%;
          animation: gradient-shift 3s ease infinite;
        }

        /* Shimmer effect */
        @keyframes shimmer {
          0% {
            background-position: -1000px 0;
          }
          100% {
            background-position: 1000px 0;
          }
        }

        .shimmer {
          background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.1), transparent);
          background-size: 1000px 100%;
          animation: shimmer 2s infinite;
        }

        /* Pulse glow for buttons */
        .pulse-glow {
          box-shadow: 0 0 0 0 rgba(168, 85, 247, 0.7);
          animation: pulse-glow 2s infinite;
        }

        @keyframes pulse-glow {
          0% {
            transform: scale(0.95);
            box-shadow: 0 0 0 0 rgba(168, 85, 247, 0.7);
          }
          70% {
            transform: scale(1);
            box-shadow: 0 0 0 10px rgba(168, 85, 247, 0);
          }
          100% {
            transform: scale(0.95);
            box-shadow: 0 0 0 0 rgba(168, 85, 247, 0);
          }
        }
      `}</style>
    </div>
  )
}
