import { ObjectId } from 'mongodb'

// Employee Role Types
export type EmployeeRole =
  | 'lead_generator' // Primary lead generation role
  | 'lead_qualifier' // Qualifies leads generated by others
  | 'closer' // Closes qualified leads
  | 'manager' // Manages team and oversees process
  | 'admin' // Full system access

// Employee Status Types
export type EmployeeStatus =
  | 'active' // Currently active employee
  | 'inactive' // Temporarily inactive
  | 'suspended' // Suspended from lead generation
  | 'terminated' // No longer with company

// Lead Generation Method Types
export type LeadGenMethod =
  | 'cold_calling' // Phone-based outreach
  | 'cold_emailing' // Email outreach
  | 'linkedin_outreach' // LinkedIn messaging
  | 'networking' // In-person networking
  | 'referrals' // Getting referrals from others
  | 'content_creation' // Creating content for leads
  | 'social_media' // Social media outreach

// Employee Model
export interface Employee {
  _id: ObjectId

  // Basic Information
  user_id: string // Business owner ID
  employee_id: string // Unique employee identifier
  first_name: string // Employee first name
  last_name: string // Employee last name
  email: string // Employee email
  phone?: string // Employee phone number

  // Role and Status
  role: EmployeeRole // Employee role in lead generation
  status: EmployeeStatus // Current employment status
  hire_date: Date // Date employee was hired
  termination_date?: Date // Date employee was terminated

  // Lead Generation Configuration
  assigned_methods: LeadGenMethod[] // Methods employee is trained on
  daily_lead_target: number // Daily lead generation target
  weekly_lead_target: number // Weekly lead generation target
  monthly_lead_target: number // Monthly lead generation target

  // Performance Tracking
  performance_metrics: {
    total_leads_generated: number
    total_qualified_leads: number
    total_converted_leads: number
    conversion_rate: number
    avg_lead_quality_score: number
    current_streak_days: number
    best_streak_days: number
    last_lead_date?: Date
  }

  // Compensation & Incentives
  compensation_model: {
    base_salary?: number // Monthly base salary
    commission_per_lead?: number // Commission per lead generated
    commission_per_qualified?: number // Commission per qualified lead
    commission_per_conversion?: number // Commission per conversion
    bonus_targets?: Array<{
      target: number
      reward: number
      type: 'leads' | 'qualified' | 'conversions'
    }>
  }

  // Training & Development
  training_status: {
    onboarding_completed: boolean
    training_modules_completed: string[]
    certification_level: 'beginner' | 'intermediate' | 'advanced' | 'expert'
    last_training_date?: Date
  }

  // Team Assignment
  team_id?: string // Team/department assignment
  manager_id?: string // Direct manager employee ID
  reports_to?: string // Who they report to

  // System Access
  system_permissions: {
    can_access_crm: boolean
    can_view_all_leads: boolean
    can_edit_lead_status: boolean
    can_assign_leads: boolean
    can_view_analytics: boolean
  }

  // Timestamps
  created_at: Date
  updated_at: Date
  last_active_date?: Date

  // Metadata
  notes?: string
  tags?: string[]
}

// Employee Lead Generation Activity
export interface EmployeeLeadActivity {
  _id: ObjectId

  // Activity Details
  user_id: string // Business owner ID
  employee_id: string // Employee who performed activity
  lead_id: string // Associated lead ID
  activity_type:
    | 'lead_created' // New lead generated
    | 'lead_contacted' // Lead was contacted
    | 'lead_qualified' // Lead was qualified
    | 'lead_converted' // Lead was converted
    | 'lead_rejected' // Lead was rejected
    | 'follow_up_scheduled' // Follow-up scheduled
    | 'meeting_booked' // Meeting booked
    | 'proposal_sent' // Proposal sent

  // Activity Data
  method_used: LeadGenMethod // Method used for this activity
  description: string // Activity description
  outcome: 'positive' | 'negative' | 'neutral'
  next_action?: string // Next planned action

  // Quality Metrics
  lead_quality_score?: number // 1-10 quality rating
  time_spent_minutes?: number // Time spent on activity

  // Timestamps
  created_at: Date
  scheduled_for?: Date // If this is a scheduled activity
  completed_at?: Date // When activity was completed

  // Metadata
  notes?: string
  attachments?: string[] // File attachments
}

// Employee Team Model
export interface EmployeeTeam {
  _id: ObjectId

  // Team Details
  user_id: string // Business owner ID
  team_name: string // Team name
  team_description?: string // Team description
  manager_id: string // Team manager employee ID

  // Team Configuration
  team_targets: {
    daily_leads: number
    weekly_leads: number
    monthly_leads: number
    quarterly_leads: number
  }

  // Team Members
  member_ids: string[] // Array of employee IDs
  member_count: number // Current team size

  // Performance Metrics
  team_performance: {
    total_leads_generated: number
    total_qualified_leads: number
    total_converted_leads: number
    team_conversion_rate: number
    avg_lead_quality: number
    current_month_leads: number
    last_month_leads: number
  }

  // Team Settings
  collaboration_settings: {
    lead_sharing_enabled: boolean
    team_leaderboard_enabled: boolean
    peer_review_enabled: boolean
    team_challenges_enabled: boolean
  }

  // Timestamps
  created_at: Date
  updated_at: Date
}

// Employee Performance Report
export interface EmployeePerformanceReport {
  _id: ObjectId

  // Report Details
  user_id: string // Business owner ID
  employee_id: string // Employee ID
  report_period: 'daily' | 'weekly' | 'monthly' | 'quarterly'
  period_start: Date
  period_end: Date

  // Lead Generation Metrics
  leads_generated: number
  qualified_leads: number
  converted_leads: number
  rejected_leads: number

  // Quality Metrics
  avg_lead_quality_score: number
  conversion_rate: number
  qualification_rate: number

  // Activity Metrics
  total_activities: number
  avg_activities_per_day: number
  total_time_spent_hours: number

  // Method Performance
  method_performance: {
    [key in LeadGenMethod]: {
      leads_generated: number
      conversion_rate: number
      time_spent_hours: number
    }
  }

  // Target Achievement
  target_achievement: {
    daily_target_hit_rate: number
    weekly_target_hit_rate: number
    monthly_target_hit_rate: number
    current_streak: number
  }

  // Ranking
  team_ranking?: number // Position in team
  company_ranking?: number // Position in company

  // Improvement Areas
  improvement_suggestions: string[]
  strengths: string[]

  // Timestamps
  generated_at: Date

  // Metadata
  notes?: string
}

// Employee Training Module
export interface EmployeeTrainingModule {
  _id: ObjectId

  // Module Details
  user_id: string // Business owner ID
  module_name: string // Training module name
  module_description: string // Module description
  module_type:
    | 'onboarding' // New employee onboarding
    | 'skill_development' // Skill improvement
    | 'product_training' // Product knowledge
    | 'system_training' // System/tool training
    | 'certification' // Certification program

  // Module Content
  content_url?: string // Link to training content
  content_text?: string // Text-based content
  video_url?: string // Training video URL
  duration_minutes: number // Expected completion time

  // Requirements
  prerequisites: string[] // Required prior modules
  required_for_roles: EmployeeRole[] // Which roles must complete

  // Completion Tracking
  completion_rate: number // % of employees who completed
  avg_completion_time: number // Average time to complete

  // Status
  status: 'active' | 'draft' | 'archived'

  // Timestamps
  created_at: Date
  updated_at: Date
}

// Employee Training Progress
export interface EmployeeTrainingProgress {
  _id: ObjectId

  // Progress Details
  user_id: string // Business owner ID
  employee_id: string // Employee ID
  module_id: string // Training module ID

  // Progress Status
  status: 'not_started' | 'in_progress' | 'completed' | 'failed'
  progress_percentage: number // 0-100 completion percentage

  // Completion Data
  started_at?: Date
  completed_at?: Date
  time_spent_minutes?: number

  // Assessment Results
  quiz_score?: number // Quiz score if applicable
  certification_earned?: boolean

  // Timestamps
  created_at: Date
  updated_at: Date
}

export type {
  EmployeeRole,
  EmployeeStatus,
  LeadGenMethod,
  Employee,
  EmployeeLeadActivity,
  EmployeeTeam,
  EmployeePerformanceReport,
  EmployeeTrainingModule,
  EmployeeTrainingProgress,
}
