import { NextResponse } from 'next/server'
import { getServerSession } from 'next-auth/next'
import { authOptions } from '@/lib/auth-config'
import { authService } from '@/lib/auth'
import clientPromise from '@/lib/mongodb'

export async function GET() {
  try {
    const session = await getServerSession(authOptions)

    if (!session?.user?.email) {
      return NextResponse.json({ error: 'Authentication required' }, { status: 401 })
    }

    // Get user profile data
    let user = await authService.getUserByEmail(session.user.email)

    if (!user) {
      return NextResponse.json({ error: 'User not found' }, { status: 404 })
    }

    // Create user profile if it doesn't exist
    if (!user.profile) {
      try {
        const profile = await authService.createUserProfile(user._id.toString(), session.user.email)
        user.profile = profile
      } catch (error) {
        console.error('Error creating user profile:', error)
        // Continue without profile if creation fails
      }
    }

    // Get real data from collections
    const client = await clientPromise
    const db = client.db()

    // Count total offers generated by this user
    const totalOffers = await db.collection('grand_slam_offers').countDocuments({
      user_id: user._id.toString(),
    })

    // Count purchased offers by this user (using email for purchased_offers collection)
    const purchasedOffers = await db.collection('purchased_offers').countDocuments({
      userId: session.user.email,
    })

    // Get the latest offer to determine last generation date
    const latestOffer = await db
      .collection('grand_slam_offers')
      .findOne({ user_id: user._id.toString() }, { sort: { created_at: -1 } })

    // Check daily generation count (offers created today)
    const today = new Date()
    const startOfDay = new Date(today.getFullYear(), today.getMonth(), today.getDate())
    const endOfDay = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1)

    const dailyGenerationCount = await db.collection('grand_slam_offers').countDocuments({
      user_id: user._id.toString(),
      created_at: {
        $gte: startOfDay.toISOString(),
        $lt: endOfDay.toISOString(),
      },
    })

    // Calculate this month's offers
    const currentMonth = new Date().getMonth()
    const currentYear = new Date().getFullYear()
    const startOfMonth = new Date(currentYear, currentMonth, 1)
    const endOfMonth = new Date(currentYear, currentMonth + 1, 1)

    const thisMonth = await db.collection('grand_slam_offers').countDocuments({
      user_id: user._id.toString(),
      created_at: {
        $gte: startOfMonth.toISOString(),
        $lt: endOfMonth.toISOString(),
      },
    })

    const usageStats = {
      totalOffers,
      thisMonth,
      creditsUsed: user.profile?.credits_used || 0,
      creditsRemaining: Math.max(0, 3 - totalOffers), // 3 free offers max
      subscriptionTier: user.profile?.subscription_tier || 'free',
      memberSince: (user as any).createdAt || new Date().toISOString(),
      purchasedOffers,
      dailyGenerationCount,
      lastGenerationDate: latestOffer?.created_at || null,
      profile: user.profile,
    }

    return NextResponse.json(usageStats)
  } catch (error) {
    console.error('Error fetching user profile:', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
